### ISSUE TITLE
Confusing Error when Profile Picture is Too Large

### ISSUE THREAD

**Issue by wmboyles** [bnussman/beep#1]
When a new user attempts to sign up and uploads a profile picture that is too large, the user sees an error saying "Unexpected token < in JSON at position 0", and graphql returns a 413 error.

![image](https://user-images.githubusercontent.com/40878829/163527955-db33e79d-31f5-4203-9432-ab41a01409bc.png)

Instead, the user should be told that the picture they attempted to upload is too large, and they need to upload a photo smaller than some maximum size.

**Comment by bnussman** [comment]
Fixed this by increasing max body size on edge nginx server and on the Kubernetes Ingress config. Thanks for reporting, I've been putting this off for far too long
