### ISSUE TITLE
Improve `Group Size` client side input and validation

### ISSUE THREAD

**Issue by TheTeaCup** [bnussman/beep#83]
## 🪲 Describe the Bug
For the group size if you repeatedly click a number you can get a group size of "infinity"

## ↩️  How to Reproduce 
On the Ride menu if you click the group size and press any number repeatedly you can list your group size as "infinity"

## 📷 Screenshots
![image](https://github.com/bnussman/beep/assets/35646791/c7c4efd6-cfcc-4dfa-b524-b44503ac54a4)

Could we get a cap on the group size? I know some people might be able to hold more than 10 people so maybe 30 or less as the group size limit?

**Comment by bnussman** [comment]
Yeah. We should probably have some client side validation for this. The server will validate the group size, so I'm not super worried about it.
