### ISSUE TITLE
test: Add e2e test for a beep with more than one rider

### ISSUE THREAD

**Issue by bnussman** [bnussman/beep#96]
Create a Playwright test that simulates two riders getting a beep from the same beeper.

Currently we have a test that simulates a beep between a beeper and one rider. We should do a similar test that does the same thing but with more than just one rider. 
https://github.com/bnussman/beep/blob/14001535028f2e4f3256b4e2a7e2dcbd956b6f7e/test/tests/beep.spec.ts#L4

**Comment by dylanmason** [comment]
https://github.com/bnussman/beep/pull/100
